### ISSUE TITLE
Test data

### ISSUE THREAD

**Issue by LJY-RS** [erik-nelson/blam#1]
Hi nelson! This is really a cool job. Did you test the BLAM package in Kitti dataset? In addition, could you share the dataset that you used? Thank you very much!

**Comment by erik-nelson** [comment]
Hey, thanks!

I didn't test it on KITTI yet, since I didn't see any .bag files to test
with and didn't feel like parsing their single-scan files. I probably will
within the next couple of months. One possible dataset to test with is
here: http://wiki.ros.org/loam_velodyne. Download the "NSH indoor outdoor"
one. Seems to work pretty well :)

Cheers!
Erik

On Mon, Jun 27, 2016 at 6:26 PM, sunrainljy notifications@github.com
wrote:

> Hi nelson! This is really a cool job. Did you test the BLAM package in
> Kitti dataset? In addition, could you share the dataset that you used?
> Thank you very much!
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/erik-nelson/blam/issues/1, or mute the thread
> https://github.com/notifications/unsubscribe/ACGSX03ntPlL0wpSpUKZogRfc0_o-3VEks5qQHhVgaJpZM4I_qGM
> .

## 

Erik Nelson
PhD Student, EECS
University of California, Berkeley
eanelson@eecs.berkeley.edu

**Comment by LJY-RS** [comment]
Hey nelson, Thanks!
I run the "NSH indoor outdoor" dataset. it performs well at the beginning, however, some mistakes happen when the trajectory goes into a small room. The results are shown in the following figure.
![res](https://cloud.githubusercontent.com/assets/19298664/16403048/e8bc003a-3d23-11e6-8a3b-ae94907f0892.png)
I run the dataset with default parameters. Should I tune the parameters? Do you meet the same problem?
Thank you very much for your consideration.
Best regards!

**Comment by erik-nelson** [comment]
Hmm, which launch file are you running? My laptop and 2 lab computers I've tested on run this dataset just fine. If you're replaying the bag file back in real-time (via the online launch file) you could be throttling your processor, and should try the offline launch file instead. Make sure the time scale parameter is set to -1.0 so the messages play back as fast as your CPU can handle them and no faster.

If you're already doing that, I'll take a look tomorrow. You shouldn't have to tune any parameters to get VLP-16 data to work.

**Comment by LJY-RS** [comment]
Very thanks! I tried as you said and got a much better results. The results are as follows：
![re1](https://cloud.githubusercontent.com/assets/19298664/16437429/69bd84f0-3dd9-11e6-8c01-b44a4e27fd6c.png)
![re2](https://cloud.githubusercontent.com/assets/19298664/16437432/6df7346c-3dd9-11e6-9cb9-39dc97648d6f.jpg)

There is no mistake in this result. There is only some small drift!
Best regards!
