### ISSUE TITLE
./update: line 13: catkin_make_isolated: command not found

### ISSUE THREAD

**Issue by camel007** [erik-nelson/blam#2]

**Comment by erik-nelson** [comment]
You will need to download and install [ROS](http://wiki.ros.org/ROS/Installation) first. See the dependencies section of [README](https://github.com/erik-nelson/blam/blob/master/README.md).

**Comment by hachbani2019** [comment]
Hello, 

Im having the same issue, I already have ROS and been using it for months, encountering the same issue for ./update
