### ISSUE TITLE
IMU information

### ISSUE THREAD

**Issue by LJY-RS** [erik-nelson/blam#4]
dear nelson:
Hi, I want to know if BLAM can integrate the IMU information to improve robust and accuracy? thanks a lot.
Good lucks!

**Comment by erik-nelson** [comment]
IMU fusion is not built into BLAM right now, and probably won't be for a while. In the next 6 months I do plan to add monocular visual odometry to color point clouds and make odometry more accurate.

**Comment by nikitaporje** [comment]
@sunrainljy did you try to interat IMU info with Blam??
