### ISSUE TITLE
test_offline run error ..

### ISSUE THREAD

**Issue by v1ljxx** [erik-nelson/blam#56]
When I run blam_example/test_offline ,I have this problem:(use velodyne.bag)

PARAMETERS
 * /blam/blam_slam/check_for_loop_closures: True
 * /blam/blam_slam/filename/bag: /home/v1/velodyne.bag
 * /blam/blam_slam/filtering/decimate_percentage: 0.9
 * /blam/blam_slam/filtering/grid_filter: True
 * /blam/blam_slam/filtering/grid_res: 0.2
 * /blam/blam_slam/filtering/outlier_filter: False
 * /blam/blam_slam/filtering/outlier_knn: 10
 * /blam/blam_slam/filtering/outlier_std: 1.0
 * /blam/blam_slam/filtering/radius: 0.15
 * /blam/blam_slam/filtering/radius_filter: False
 * /blam/blam_slam/filtering/radius_knn: 3
 * /blam/blam_slam/filtering/random_filter: True
 * /blam/blam_slam/frame_id/base: base
 * /blam/blam_slam/frame_id/fixed: world
 * /blam/blam_slam/frame_id/odometry: odometry
 * /blam/blam_slam/icp/corr_dist: 2.0
 * /blam/blam_slam/icp/iterations: 10
 * /blam/blam_slam/icp/max_rotation: 0.1
 * /blam/blam_slam/icp/max_translation: 0.09
 * /blam/blam_slam/icp/tf_epsilon: 1e-10
 * /blam/blam_slam/icp/transform_thresholding: False
 * /blam/blam_slam/init/orientation/pitch: 0.0
 * /blam/blam_slam/init/orientation/roll: 0.0
 * /blam/blam_slam/init/orientation/yaw: 0.0
 * /blam/blam_slam/init/orientation_sigma/pitch: 0.02
 * /blam/blam_slam/init/orientation_sigma/roll: 0.02
 * /blam/blam_slam/init/orientation_sigma/yaw: 0.02
 * /blam/blam_slam/init/position/x: 0.0
 * /blam/blam_slam/init/position/y: 0.0
 * /blam/blam_slam/init/position/z: 0.0
 * /blam/blam_slam/init/position_sigma/x: 0.1
 * /blam/blam_slam/init/position_sigma/y: 0.1
 * /blam/blam_slam/init/position_sigma/z: 0.1
 * /blam/blam_slam/localization/corr_dist: 1.0
 * /blam/blam_slam/localization/iterations: 10
 * /blam/blam_slam/localization/max_rotation: 0.1
 * /blam/blam_slam/localization/max_translation: 0.05
 * /blam/blam_slam/localization/tf_epsilon: 1e-10
 * /blam/blam_slam/localization/transform_thresholding: False
 * /blam/blam_slam/map/octree_resolution: 0.05
 * /blam/blam_slam/max_tolerable_fitness: 0.15
 * /blam/blam_slam/poses_before_reclosing: 40
 * /blam/blam_slam/proximity_threshold: 1.5
 * /blam/blam_slam/rate/estimate: 20.0
 * /blam/blam_slam/rate/visualization: 0.5
 * /blam/blam_slam/relinearize_skip: 1
 * /blam/blam_slam/relinearize_threshold: 0.01
 * /blam/blam_slam/scan_topic: /velodyne_points
 * /blam/blam_slam/skip_recent_poses: 40
 * /blam/blam_slam/time_end: -1.0
 * /blam/blam_slam/time_scale: -1.0
 * /blam/blam_slam/time_start: 0.0
 * /blam/blam_slam/translation_threshold: 0.5
 * /rosdistro: melodic
 * /rosversion: 1.14.3
 * /use_sim_time: False

NODES
  /blam/
    blam_slam (blam_slam/blam_slam_offline)

ROS_MASTER_URI=http://localhost:11311

process[blam/blam_slam-1]: started with pid [21523]
[ INFO] [1578214928.172843610]: /blam/blam_slam/BlamSlam: Registering log callbacks.
[ INFO] [1578214928.177684955]: /blam/blam_slam/BlamSlamOffline: Processing the following topics:
	/velodyne_points

**(this problem)**
[blam/blam_slam-1] process has died [pid 21523, exit code -11, cmd /home/v1/blam/internal/devel/lib/blam_slam/blam_slam_offline __name:=blam_slam __log:=/home/v1/.ros/log/993d7596-2f98-11ea-beb4-40e2307786c1/blam-blam_slam-1.log].
log file: /home/v1/.ros/log/993d7596-2f98-11ea-beb4-40e2307786c1/blam-blam_slam-1*.log

all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Anyone met this problem? Please help me.

**Comment by GabrieleGalimberti-GaleSelector** [comment]
Hi,
How you solved the issue?
